networks:
    main_network:

volumes:
    keycloak_volume:

services:
    database:
        build: ./database
        networks: [main_network]
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: app
            MONGO_INITDB_ROOT_PASSWORD: app
        volumes:
            - ./database/.volume:/data/db

    dbmanager:
        image: mongo-express
        networks: [main_network]
        depends_on: [database]
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: database
            ME_CONFIG_MONGODB_ADMINUSERNAME: app
            ME_CONFIG_MONGODB_ADMINPASSWORD: app
            ME_CONFIG_BASICAUTH_USERNAME: app
            ME_CONFIG_BASICAUTH_PASSWORD: app
            ME_CONFIG_MONGODB_URL: mongodb://app:app@database:27017/admin

    backend:
        build: ./backend
        networks: [main_network]
        depends_on: [database]
        volumes:
            - ./backend/app:/var/www/html
        ports:
            - 8000:80

    keycloak:
        build: ./keycloak
        networks: [main_network]
        depends_on: [database, backend]
        environment:
            # KC_DB: postgres
            # KC_DB_URL_HOST: database
            # KC_DB_URL_DATABASE: app
            # KC_DB_USERNAME: app
            # KC_DB_PASSWORD: app
            KEYCLOAK_ADMIN: app
            KEYCLOAK_ADMIN_PASSWORD: app
            WEBHOOK_HTTP_BASE_PATH: "http://backend/api/app/keycloak_webhook"
            WEBHOOK_HTTP_AUTH_USERNAME: "app"
            WEBHOOK_HTTP_AUTH_PASSWORD: "app"
        volumes:
            - ./keycloak/providers:/opt/keycloak/providers
            # - ./keycloak/themes:/opt/keycloak/themes
            - keycloak_volume:/opt/keycloak/data/
        ports:
            - 8080:8080

    frontend:
        build: ./frontend/
        volumes:
            - ./frontend/app:/app
        ports:
            - 3000:3000

    minio:
        image: minio/minio:latest
        networks: [main_network]
        command: server /data --console-address ":9001"
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
            MINIO_API_CORS_ALLOW_ORIGIN: "*"
            MINIO_DEFAULT_BUCKETS: app
        volumes:
            - ./minio/.data:/data

    rabbitmq:
        image: rabbitmq:3-management
        networks: [main_network]
        environment:
            RABBITMQ_DEFAULT_USER: app
            RABBITMQ_DEFAULT_PASS: app
        # volumes:
        #     - ./rabbitmq/.lib:/var/lib/rabbitmq
        #     - ./rabbitmq/.log:/var/log/rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
